name: Tangti Dotnet

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "main"
      - "dev"

env:
  DOTNET_VERSION : '7.0.x'
  AZURE_WEBAPP_NAME: 'tangtiwebapp'
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Setup dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run : dotnet restore

      - name: Build app
        run : dotnet build -c Release --no-restore
      
      - name: Publish app
        run : dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}

      - name: Upload artifact for deploymeny job
        uses: actions/upload-artifact@v3
        with:
          name: tangti.net-app
          path: ${{ env.DOTNET_ROOT }}/tangti

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Tangti Deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: tangti.net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.ASP_CORE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}