name: Tangti Dotnet

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "main"
      - "dev"

env:
  AZURE_WEBAPP_NAME: 'Tangti'
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x', '8.0.x' ]
        
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run : dotnet restore

      - name: Build app
        run : dotnet build -c Release --no-restore
      
      - name: Publish app
        run : dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}

      - name: Upload artifact for deploymeny job
        uses: actions/upload-artifact@v4
        with:
          name: tangti-${{ matrix.dotnet-version }}.net-app
          path: ${{ env.DOTNET_ROOT }}/tangti

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Tangti Deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: tangti.net-app
      
      - name: Deplot to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.ASP_CORE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}