name : Dotnet

on:
    push:
        branches:
            - "dev"
            - "main"
    pull_request:
        branches:
            - "main"

env:
    DOTNET_VERSION: '7.0.x'
    AZURE_WEBAPP_NAME: kmitltangti
    AZURE_WEBAPP_PACKAGE_PATH: '.'
    
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        -   name: Check out code
            uses: actions/checkout@v3
        -   name: Setup .Net
            uses: actions/setup-dotnet@v2
            with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
        -   name: Restore rependencies
            run : dotnet restore

        -   name: Build app
            run : dotnet build -c Release --no-restore

        -   name: Test
            run : dotnet test --no-build --verbosity normal

        -   name: dotnet publish
            run : dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

        -   name: Upload artifact for deployment job
            uses: actions/upload-artifact@v3
            with:
                name: kmitltangti.net-app
                path: ${{env.DOTNET_ROOT}}/myapp

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Development'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
        -   name: Download atifact from build job
            uses: actions/download-artifact@v3
            with:
                name: kmitltangti.net-app
        
        -   name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.ASP_CORE_PUBLISH_PROFILE }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}